#!/usr/bin/env bash
# Change your home IP address
HOSTS_FILE="/etc/hosts"

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root (sudo $0)"
  exit 1
fi

sed -i '/localhost/d' "$HOSTS_FILE"
sed -i '/facebook.com/d' "$HOSTS_FILE"

echo "127.0.0.2 localhost" >> "$HOSTS_FILE"
echo "8.8.8.8 facebook.com" >> "$HOSTS_FILE"

echo "Modifications appliquées à $HOSTS_FILE"
